/**
 * @fileOverview digo 语言包：中文(简体)
 * @author xuld <xuld@vip.qq.com>
 * @license MIT
 * @see https://github.com/mishoo/UglifyJS2
 */

module.exports = {
    "Specify the current working directory.": "指定当前工作目录",
    "Specify the config file. Defaults to 'tpack.config.js'.": "指定配置文件。默认为 'tpack.config.js'。",
    "Disable features that require global modules from config file.": "禁止从配置文件直接载入全局安装的模块。",
    "Add ignored path.": "添加忽略路径。",
    "Load specified ignore file. e.g. '--ignore-file .gitignore'.": "载入指定忽略文件。如 '--ignore-file .gitignore'。",
    "Process files of whole project rather than current directory.": "生成整个项目。",
	"Pipe a processor for all inputs.": "添加所有文件的生成器。",
    "Specify the ui language.": "指定界面语言。",
    "Enable debug mode.": "启用调试模式。",
    "Specify the default encoding. Defaults to 'utf-8'.": "指定默认编码。默认为 'utf-8'。",
    "Enable overwriting source files.": "允许覆盖源文件。",
    "Enable generating files out of output directory.": "允许保存文件到目标文件夹外部。",
    "Disable colorized outout.": "禁用控制台颜色。",
    "Print logs. This will implicitly hide the progress bar.": "打印日志。同时隐藏进度条动画。",
    "Print errors only.": "只打印错误。",
    "Print errors and warnings only.": "只打印错误和警告。",
    "Print errors, warnings and necessary informations only.": "只打印错误、警告和关键信息。",
    "Disable all outputs.": "禁用所有输出。",
    "Print full path in outputs.": "输出时使用完整路径。",
    "Do not clean output directory when building.": "生成时不清理目标文件夹。",
    "Specify the output directory.": "指定目标文件夹。",
    "Gernate source maps if available.": "生成源码映射表。",
    "Inline source maps in output files.": "内联生成的源码映射表。",
    "Include sources in source maps.": "在源码映射表中包含源文件。",
    "Specify url prefix for source maps.": "设置源码映射表中的地址前缀。",
    "Specify port of dev-server.": "指定开发服务器的端口。",
	"Specify url of dev-server.": "指定开发服务器的地址。",
    "Enable passive mode for dev-server.": "启用开发服务器被动模式。",
    "Enable hot loader for dev-server.": "启用开发服务器的热加载。",
    "Build all files once.": "生成所有文件一次。",
    "Watch files.": "监听文件。",
    "Start a dev-server.": "打开开发服务器。",
    "Delete build outputs.": "删除生成文件。",
    "Build all files once without saving.": "生成但不保存。",
    "Print the current version of tpack.": "打印 TPack 的版本号。",
    "Create 'tpack.config.js' in current directory.": "在当前文件夹新建 'tpack.config.js' 文件。",
    "File '{path}' exists already. Nothing done.": "文件 '{path}' 已存在。未执行操作。",
    "File '{path}' is created successfully.": "文件 '{path}' 创建成功。",
	"Specify the input file.": "指定输入文件。",
    "Print this message.": "打印本信息",
	"Initialize tab completion for current bash.": "初始化 Bash Tab 提示支持。",
	
    "\nUsage: tpack <task> [options] [files ...]": "\n用法: tpack <任务> [选项] [文件列表 ...]",
    "Options": "选项",
    "Print all tasks defined in config file.": "打印所有已定义的任务。",
    "Option '{option}' is not supported yet.": "选项 '{option}' 暂不支持。",
    "Cannot find 'tpack.config.js'. Run 'tpack --init' to create here.": "找不到 'tpack.config.js'。可以执行 'tpack --init' 创建。",
    "Error loading '{config}': {message}": "加载配置文件 '{config}' 出错: {message}",
    "TPack: '{tpack}' (v{version}).": "TPack: '{tpack}' (版本 {version})。",
    "Config: '{config}'.": "配置文件: '{config}'。",
    "Defined Tasks": "已定义的任务",
    "Task '{task}' is not defind.": "任务 '{task}' 未定义。",
    "Error executing task '{task}': {message}": "执行任务 '{task}' 出错: {message}",
	
	"Cannot overwrite source file. Use '--overflow' to force saving.": "无法覆盖源文件。使用 '--overflow' 强制覆盖。",

    "> Start Building...": "> 开始生成...",
    "> Build Completed! ({0} files saved, {1} error(s) found)": "> 生成完成（已生成：{0} 文件，错误：{1}）",
    "> Build Success! ({0} files saved, without errors)": "> 生成成功（已生成：{0} 文件，无错误）",
    "> Cleaning...": "> 清理目标文件夹...",
    "> Processing Files...": "> 生成文件...",
    "{0}: Uncaught error: {1}": "{0}: 未捕获的错误: {1}",
    "> Executing Rule {0}": "> 执行规则 {0}",
    "> Watching {srcPath} ...": "> 正在监听 {basePath} ...",
    "> Server Running At {rootUrl}": "> 已启动服务器： {rootUrl}",
    "> Server Stopped At {rootUrl}": "> 已停止服务器： {rootUrl}",
    "Create Server Error: Port {port} of {address} is used by other programs.": "无法启动服务器: {address} 上的端口 {port} 已被其它程序占用",
    "Create Server Error: Port {port} is used by other programs.": "无法启动服务器: 端口 {port} 已被其它程序占用",
    "File '{0}' exists already. Nothing done.": "文件 '{0}' 已存在。未进行操作。",
    "File '{0}' is created successfully.": "文件已成功创建: '{0}'",
    "Task '{0}' is not defind. Use 'tpack -?' for more informations.": "任务 '{0}' 未定义。使用 'tpack -?' 查看更多信息。"
};